services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    ports:
      - 5432:5432

  minio:
    image: minio/minio
    expose:
      - 9000
      - 9001
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - ./data/objectstore:/data


volumes:
  local_postgres_data: {}
  redbox-app-data:
